#!/bin/bash

for region in `cat ~/scripts/region_names`; do for stage in Prod OneBox; do while read monitor; do mon_name=`echo $monitor | sed -e "s/REGION/$region/g" -e "s/STAGE/$stage/g" -e "s/ /%20/g"`; echo $mon_name; mon_id=`mcurl -q "https://carnaval.amazon.com/v1/controlMonitor.do?name=$mon_name&command=delete" | egrep -i 'hidden" name="id" value="[0-9]*"' | sed -e 's/.*value="\([0-9]*\).*/\1/g'`; [ -n $mon_id ] && mcurl -X POST -F "command=delete" -F "id=$mon_id" "https://carnaval.amazon.com/v1/controlMonitorSubmit.do?name=$mon_name&command=delete"; done < mon_names; done; done
